BEGIN;
CREATE TABLE IF NOT EXISTS public.omgithub_projects (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS public.project_social (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS public.project_ratings (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS public.project_comments (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS public.project_plays (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE INDEX IF NOT EXISTS projects_slug ON public.omgithub_projects ((data->>'slug'));
CREATE INDEX IF NOT EXISTS projects_source_key ON public.omgithub_projects ((data->>'source_key'));
CREATE INDEX IF NOT EXISTS projects_public_path ON public.omgithub_projects ((data->>'public_path'));
CREATE INDEX IF NOT EXISTS projects_published_at ON public.omgithub_projects ((data->>'published_at') DESC);
CREATE INDEX IF NOT EXISTS comments_project ON public.project_comments ((data->>'project_id'));
ALTER TABLE public.omgithub_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_social ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_plays ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.omgithub_projects, public.project_social, public.project_ratings, public.project_comments, public.project_plays FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.omgithub_projects, public.project_social, public.project_ratings, public.project_comments, public.project_plays TO service_role;
COMMIT;
